version: "3.9"

services:
  app:
    build: .
    image: nodejs-checkpoint-hours
    container_name: nodejs-checkpoint-hours
    restart: unless-stopped
    env_file: .env
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app